

// All these values could be stored in the database.

/// default gravity
#define GRAVITY -6.0


#define PHYSICS_STEP 0.0166

//#define LINEAR_DAMPING 0.5
#define LINEAR_DAMPING 1.0
#define THRUST_FORCE 150.0



// #define ANGULAR_DAMPING 20.0
//#define ANGULAR_FORCE 60.0
//#define ANGULAR_FORCE_RECOVER 120.0

#define ANGULAR_DAMPING 20.0
#define ANGULAR_FORCE 60.0
#define ANGULAR_FORCE_RECOVER 120.0




#define SMALL_CONTACT_THRESHOLD 0.01
#define SMALL_CONTACT_MULTIPLICATOR 0.5f
#define SMALL_CONTACT_MULTIPLICATOR_EASY 1.0f
#define SMALL_CONTACT_MULTIPLICATOR_NORMAL 5.0f
#define SMALL_CONTACT_MULTIPLICATOR_HARD 10.0f

#define BIG_CONTACT_THRESHOLD 0.02
#define BIG_CONTACT_MULTIPLICATOR 0.5f
#define BIG_CONTACT_MULTIPLICATOR_EASY 1.0f
#define BIG_CONTACT_MULTIPLICATOR_NORMAL 20.0f
#define BIG_CONTACT_MULTIPLICATOR_HARD 50.0f


#define FUEL_CONSUMPTION_EASY 0.01
#define FUEL_CONSUMPTION_NORMAL 0.02
#define FUEL_CONSUMPTION_HARD 0.04


// these can be extracted from the database !
#define LEVEL_MAX_TERRAINTEXTURES 14
#define LEVEL_MAX_DETAILTEXTURES 3
#define LEVEL_MAX_HEIGHTMAPS 14
