


#ifndef _HOPPER_EMITTER_TYPES_
#define _HOPPER_EMITTER_TYPES_

enum HOPPER_PARTICLES {

    PART_TERRAIN_SMOKE=0,
    PART_DARK_SMOKE,
    PART_COLLISION_SPARKS,
    PART_THRUSTER_SPARKS,
    PART_EXPLOSION,
    PART_AIRDUST,
    PART_PROJECTILE_HIT,
    PART_THRUSTER_SMOKE,
    MAX_EMITTER_TYPE

};

#endif
