

#ifndef _HOPPERSOUNDS_
#define _HOPPERSOUNDS_


#define SOUND_THRUST 0
#define SOUND_GROUND_HIT 1
#define SOUND_LANDED 2
#define SOUND_EXPLODE 3
#define SOUND_REFUEL 4
#define SOUND_REFUEL_OK 5
#define SOUND_OUTOFFUEL 6
#define SOUND_SCRATCH 7
#define SOUND_THRUSTLOOP 8
#define SOUND_FREEZING 9
#define SOUND_FAN 10
#define SOUND_WRONGRING 11
#define SOUND_MOUSECLICK 12
#define SOUND_PLASTIC 13
#define SOUND_METAL_HIT 14
#define SOUND_FUEL_LOW 15
#define SOUND_HULL_CRITICAL 16
#define SOUND_UNFREEZING 17
#define SOUND_PULSE 18
#define SOUND_PROJECTILE_HIT 19
#define SOUND_PROXMINE 20
#define SOUND_TURRET 21
#define SOUND_WINDMILL 22

#define SOUND_THREE 23
#define SOUND_TWO 24
#define SOUND_ONE 25
#define SOUND_GO 26

#define SOUND_TRACTORBEAM 27

#define SOUND_LAST_SOUND 28

#endif


